defmodule Color.Palette.Visualizer.Render do
  @moduledoc false

  # Shared HTML helpers. Pure functions, no templates, iodata in /
  # iodata out. All literal markup is written as double-quoted
  # strings so it's immune to Elixir's sigil-vs-keyword edge
  # cases around colons.

  @doc "HTML-escapes a binary."
  @spec escape(iodata()) :: iodata()
  def escape(iodata) when is_list(iodata), do: Enum.map(iodata, &escape/1)

  def escape(binary) when is_binary(binary) do
    binary
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
    |> String.replace("'", "&#39;")
  end

  def escape(other), do: escape(to_string(other))

  @doc "Wraps body iodata in the full HTML page chrome."
  def page(assigns) do
    title = Keyword.fetch!(assigns, :title)
    active = Keyword.fetch!(assigns, :active)
    seed = Keyword.get(assigns, :seed, "")
    body = Keyword.fetch!(assigns, :body)
    error = Keyword.get(assigns, :error)
    base = Keyword.fetch!(assigns, :base)
    extra_fields = Keyword.get(assigns, :extra_fields, [])

    [
      "<!doctype html><html lang=\"en\"><head>",
      "<meta charset=\"utf-8\">",
      "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
      "<title>",
      escape(title),
      " — Color.Palette.Visualizer</title>",
      "<link rel=\"stylesheet\" href=\"",
      escape(base),
      "/assets/style.css\">",
      "</head><body>",
      header(active, seed, base, extra_fields),
      "<main class=\"vz-main\">",
      error_block(error),
      body,
      footer(),
      "</main></body></html>"
    ]
  end

  defp header(active, seed, base, extra_fields) do
    tabs = [{"tonal", "Tonal"}, {"theme", "Theme"}, {"contrast", "Contrast"}]

    [
      "<header class=\"vz-header\">",
      "<h1>Color.Palette.Visualizer</h1>",
      "<nav class=\"vz-tabs\">",
      Enum.map(tabs, fn {path, label} ->
        cls = if path == active, do: "active", else: ""

        [
          "<a href=\"",
          escape(base),
          "/",
          path,
          "\" class=\"",
          cls,
          "\">",
          label,
          "</a>"
        ]
      end),
      "</nav>",
      "<form class=\"vz-form\" method=\"get\" action=\"",
      escape(base),
      "/",
      active,
      "\">",
      "<label>seed <input type=\"text\" name=\"seed\" value=\"",
      escape(seed),
      "\" placeholder=\"#3b82f6\"></label>",
      extra_fields,
      "<button type=\"submit\">Update</button>",
      "</form>",
      "</header>"
    ]
  end

  defp error_block(nil), do: []

  defp error_block(message) do
    ["<div class=\"vz-error\">", escape(message), "</div>"]
  end

  defp footer do
    [
      "<div class=\"vz-footer\">",
      "Generated by ",
      "<a href=\"https://hexdocs.pm/color/Color.Palette.html\">Color.Palette</a>",
      "</div>"
    ]
  end

  @doc "Renders one tonal-scale strip as a grid of swatches."
  def tonal_strip(%Color.Palette.Tonal{} = palette) do
    labels = Color.Palette.Tonal.labels(palette)

    [
      "<div class=\"vz-strip\">",
      Enum.map(labels, &swatch(palette, &1)),
      "</div>"
    ]
  end

  defp swatch(palette, label) do
    color = Map.fetch!(palette.stops, label)
    hex = Color.to_hex(color)
    {:ok, oklch} = Color.convert(color, Color.Oklch)
    text_color = text_on(color)

    seed_class = if label == palette.seed_stop, do: " vz-seed", else: ""

    [
      "<div class=\"vz-swatch",
      seed_class,
      "\">",
      "<div class=\"vz-chip\" style=\"background:",
      hex,
      ";color:",
      text_color,
      "\">",
      escape(to_string(label)),
      "</div>",
      "<div class=\"vz-meta\">",
      "<div class=\"vz-hex\">",
      escape(hex),
      "</div>",
      "<div>L\u00A0",
      fmt(oklch.l, 3),
      " C\u00A0",
      fmt(oklch.c, 3),
      " H\u00A0",
      fmt(oklch.h, 1),
      "</div>",
      contrast_pair(color),
      "</div>",
      "</div>"
    ]
  end

  defp contrast_pair(color) do
    w_ratio = Color.Contrast.wcag_ratio(color, "white")
    b_ratio = Color.Contrast.wcag_ratio(color, "black")

    [
      "<div class=\"vz-contrast\">",
      "<span class=\"",
      pass_class(w_ratio),
      "\">⬜ ",
      fmt(w_ratio, 2),
      "</span>",
      "<span class=\"",
      pass_class(b_ratio),
      "\">⬛ ",
      fmt(b_ratio, 2),
      "</span>",
      "</div>"
    ]
  end

  defp pass_class(r) when r >= 4.5, do: "pass"
  defp pass_class(r) when r >= 3.0, do: "warn"
  defp pass_class(_), do: "fail"

  @doc "\"#000\" or \"#fff\", whichever has higher contrast against the given colour."
  @spec text_on(Color.input()) :: binary()
  def text_on(color) do
    white = Color.Contrast.wcag_ratio(color, "white")
    black = Color.Contrast.wcag_ratio(color, "black")
    if black > white, do: "#000", else: "#fff"
  end

  @doc "Formats a float to N decimal places."
  @spec fmt(number(), non_neg_integer()) :: binary()
  def fmt(n, places) when is_number(n), do: :erlang.float_to_binary(n * 1.0, decimals: places)
  def fmt(_, _), do: "—"
end
